# -*- coding: utf-8 -*-
"""week-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L6q4_gJWX1QhiddOB2TSRnoqbJ5-r-7F
"""

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import gutenberg
# Download the gutenberg corpus if not already installed
nltk.download('gutenberg')
nltk.download('punkt') # Ensure the punkt tokenizer models are also downloaded
nltk.download('punkt_tab') # Download punkt_tab as it was missing
# Load the text from the gutenberg corpus
sample = gutenberg.raw("austen-emma.txt") # Change to an existing text from the corpus
# Tokenize the sample text
token = word_tokenize(sample)
# Create a list of the first 50 tokens
wlist = []
for i in range(50):
    wlist.append(token[i])
# Calculate the frequency of each word in the list
wordfreq = [wlist.count(w) for w in wlist]
# Print the word-frequency pairs
print("Pairs\n" + str(list(zip(wlist, wordfreq))))